import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Sidebar } from "@/components/Sidebar";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <Providers>
      <body className={inter.className}>
        <div>
            <Sidebar />

            <div className="flex-1 flex flex-col ml-64">
                <Navbar />
          
            {children}
            
          </div>
        </div>
      </body>
      </Providers>
    </html>
  );
}
